V14 policy
mjethanandani/ietf-bgp-yang pull request #224
Opened 2022-09-16 04:14 UTC by yingzhenqu

summary of change:
added references
for community, changed type from union to string only
removed next-hop-in-eq since there is match-next-hop-set
changed afi-safi-in and neighbor-eq to container with match-set-options
changed as-path-prepend to allow any ASN prepending

2022-09-16 18:22 UTC, mjethanandani approved these changes
Just one editorial change. But I would wait on others to comment

2022-09-23 19:08 UTC, mjethanandani requested changes
@yingzhenqu , thanks for suggesting the changes. As agreed, in addition to addressing the comments in this review, please add an example that validates these changes, and "compile" the draft using the Docker container, i.e. by running make in the root folder.

2022-09-23 19:08 UTC, mjethanandani commented on src/yang/ietf-bgp-policy.yang
> +      "RFC 6991: Common YANG Data Types";
Thanks for adding these references.

2022-09-23 19:08 UTC, mjethanandani commented on src/yang/ietf-bgp-policy.yang
> +      type uint32;
Please revert these changes.

2022-09-23 19:08 UTC, mjethanandani commented on src/yang/ietf-bgp-policy.yang
> +  augment "/rt-pol:routing-policy/rt-pol:policy-definitions/"
Changes are editorial. Please revert.

2022-09-23 19:08 UTC, mjethanandani commented on src/yang/ietf-bgp-policy.yang
> +  augment "/rt-pol:routing-policy/rt-pol:policy-definitions/"
Editorial changes. Please revert.

2022-09-30 22:06 UTC, yingzhenqu commented
I've done the changes we discussed about bgp-policy.
added a configuration example in appendix.
checked the existing policy example and made sure it's still valid.
went over the oc bgp-policy model and it seems we didn't miss anything.

2022-10-07 18:10 UTC, mjethanandani approved these changes

2022-10-07 18:10 UTC, jhaas-pfrc approved these changes

2022-10-07 18:11 UTC, merged