Issue #225 A typedef for BGP color extended communities
mjethanandani/ietf-bgp-yang pull request #325
Opened 2023-01-20 21:09 UTC by jhaas-pfrc

I'm not sure we want to proceed with this commit in the initial IETF BGP YANG module, but this is a useful modeling exercise for how to solve some ugly issues.

The BGP Color community has changed in RFC 9012 from its older format to move the first 16 bits of RESERVED value into a Flags field.  SR-TE policy work has allocated two of those bits.  A number of bits are currently unknown and may be assigned further in the future.

A flexible format where, when the flags are all known, the flag fields are displayed as a comma-separated set of flag bits.  If any flag bits are unknown, or the Flags are zero, a default format to render the Flags as a uint16 is done.

Note that this varies from the OC proposal to simply display the two known flags as it doesn't cover future flag possibilities.

Closes #225

2023-01-24 00:57 UTC, suehares commented
Jeff: 
I agree with leaving the typedef for Color Community until another time. 

I did not understand this sentence: " If any flag bits are unknown, or the Flags are zero, a default format to render the Flags as a uint16 is done."

If you have the two known flag bits set, would it be "flag1, flag2".  
If you have all know known flag bits zero,  would it be "0" or "none"?

2023-01-24 00:59 UTC, suehares requested changes
I request we leave this for a later model or an augmentation (for color) of the BGP model. 
Therefore, I am asking you not to merge in the changes. 

I agree with Jeff's proposal.

2023-01-24 15:18 UTC, jhaas-pfrc commented
> Jeff: I agree with leaving the typedef for Color Community until another time.
> 
> I did not understand this sentence: " If any flag bits are unknown, or the Flags are zero, a default format to render the Flags as a uint16 is done."
> 
> If you have the two known flag bits set, would it be "flag1, flag2". If you have all know known flag bits zero, would it be "0" or "none"?

Consider the case we have right now.  RESERVED was partitioned into color-only for bits 0,1 and renamed the uint16 as Flags.

If the value of the Flags is zero, we omit it in the output for consistency with older spec.  So, color type/subtype flags=0, color=100 renders as "color:100".
If only the color-only bits are set, we render them.  For example, color:co=01:100
Let's say the value was something outside the known color-only flags and the uint16 is value 100.  We then render in the non-bit-flag format: color:100:100

In this mechanism, when we add known bits, we start adding the names.  So, if bit 2 is given the name foo, and bit 3 is bar, and co=01 and foo and bar are set with color 100, the rendered format would be color:co=01,foo,bar:100

the requirement is that the known flag bits are canonically ordered such that regular expressions can test for them.  Consider policy where you want to select color communities with color value 100 and foo set and everything else is irrelevant.  The regex would be "^color:.*foo.*:100$"

2023-01-27 06:43 UTC, keyur-arrcus reviewed
Looks good. Ok by me to leave it out for a while as Jeff and Sue discussed.

2023-06-09 16:31 UTC, suehares approved these changes

2023-12-04 05:05 UTC, mjethanandani commented
Not merging this PR as suggested by Jeff and Sue.

2023-12-04 05:05 UTC, closed without merging